<?php
/**
 * Copyright (c) 2024-2025. All rights reserved.
 * @author: Volodymyr Hryvinskyi <mailto:volodymyr@hryvinskyi.com>
 */

/**
 * @var \Hryvinskyi\PageSpeedJsMergeFrontendUi\Block\RequireJsDataCollector $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$routeKey = json_encode($block->getRouteKey());
$requestUrl = json_encode($block->getRequestUrl());
$pageCacheTags = json_encode($block->getPageCacheTags());
$ignore = json_encode($block->getIgnore());

$scriptContent = <<<JS
require(['Hryvinskyi_PageSpeedJsMergeFrontendUi/js/require-js-data-collector'], function (dataCollector) {
    dataCollector.init({$routeKey}, {$requestUrl}, {$pageCacheTags}, {$ignore});
    dataCollector.run();
});
JS;
echo $secureRenderer->renderTag(
    'script',
    [
        $block->getScriptDataKey() => $block->getRouteKey(),
        'data-pagespeed-ignore-merge' => null
    ],
    $scriptContent,
    false
);
